DWH_SPS_NAME = {'Id': 'sps_key',
                'Panel__c': 'curr_panel_key',
                'Tenant_SIM__c': 'sps_tenant_name',
                'Panel2__c': 'curr_panel2_key',
                'Panel_2_SN__c': 'curr_panel2_sn',
                'Customer_Ownership__c': 'customer_ownership_flag',
                'Payment_Method_Allowed__c': 'allowed_payment_method',
                'Subtype__c': 'sps_unit_type'
                }
DWH_CONTACT_NAME = {'Id': 'contact_key', 'AccountId': 'account_key', 'State__c': 'contact_user_state',
                    'Sales_Agent_Sub_Channel__c': 'lead_agent_sub_channel'}
DWH_USER_NAME = {'Id': 'user_key', 'ContactId': 'user_contact_key', 'Name': 'username'}
DWH_PRICBOOK_NAME = {'Id': 'price_book_key', 'Tenant_SIM__c': 'price_book_tenant', 'Ecommerce__c': 'ecommerce_flag',
                     'Generation__c': 'price_book_generation', 'Sales_Channel__c': 'price_book_sales_channel',
                     'Unit_To_Bundle_Combo__c': 'price_book_bundle_combination', 'Type__c': 'price_book_type',
                     'Name': 'price_book_name',
                     'CreatedDate': 'price_book_create_date',
                     'LastModifiedDate': 'price_book_update_date',
                     'IsActive': 'price_book_active_flag',
                     'IsDeleted': 'price_book_deleted_flag',
                     'Partner__c': 'price_book_partner_key',
                     'LastModifiedById': 'price_book_updated_user_id',
                     'CreatedById': 'price_book_created_user_id'
                     }
DWH_RECORDTYPE_NAME = {'Id': 'lead_record_type_id', 'Name': 'lead_record_type_name'}
DWH_LEAD_NAME = {'Id': 'lead_key',
                 'Sales_Agent__c': 'lead_agent_contact_key',
                 'Type__c': 'lead_type',
                 'LeadSource': 'lead_source',
                 'Partner__c': 'lead_partner',
                 'Status': 'lead_status',
                 'CreatedDate': 'lead_create_date',
                 'Name': 'lead_name',
                 'Salutation': 'lead_salutation',
                 'FirstName': 'lead_first_name',
                 'LastName': 'lead_last_name',
                 'Category__c': 'lead_category',
                 'Phone': 'lead_phone',
                 'Country__c': 'lead_country',
                 'State__c': 'lead_state',
                 'City_formula__c': 'lead_city',
                 'Street__c': 'lead_street',
                 'Email': 'lead_email',
                 'Prefered_language__c': 'lead_prefered_language',
                 'CurrencyIsoCode': 'lead_currency_code',
                 'IsConverted': 'lead_converted_flag',
                 'ConvertedDate': 'lead_converted_date',
                 'ConvertedAccountId': 'lead_converted_account_key',
                 'ConvertedContactId': 'lead_converted_contact_key',
                 'ConvertedOpportunityId': 'lead_converted_opportunity_key',
                 'RecordTypeId': 'lead_record_type_id',
                 'OwnerId': 'lead_owner_id',
                 'CreatedById': 'lead_created_by_id',
                 'LastModifiedById': 'lead_modified_by_id',
                 'LastModifiedDate': 'lead_modify_date',
                 'IsDeleted': 'lead_deleted_flag',
                 'Agent_Name__c': 'lead_agent_name',
                 'Contact_phone_number_verified__c': 'contact_phone_number_verified_flag',
                 'I_confirm_that_Guarantor_is_approved__c': 'guarantor_approved_flag',
                 'Welcome_Call_Preformed__c': 'welocome_call_performed_flag',
                 'Sub_Channel__c': 'lead_sub_channel'
                 }
DWH_INSTALLATION_NAME = {'Id': 'contract_key', 'Opportunity__c': 'contract_opportunity_key'}
